title: Dennis Ulbrich | Webseite
page-top-title:  Willkommen!
page-top-titleEN: Welcome!
top-section-bg-text: Dr. Dennis Ulbrich
Start-subtitle: Ãœber mich
copyright-text: '&copy; 2024 D. Ulbrich'

titleEN: Dennis Ulbrich | Website
Start-subtitleEN: About
