title: Dennis Ulbrich | Webseite
page-top-title:  
top-section-bg-text: Dr. Dennis Ulbrich
Start-subtitle: Willkommen auf meiner pers√∂nlichen Webseite!
copyright-text: '&copy; 2024 D. Ulbrich'

titleEN: Dennis Ulbrich | Website
Start-subtitleEN: Welcome to my personal website!
