title: Dennis Ulbrich | Webseite
page-top-title:  
top-section-bg-text: Dr. Dennis Ulbrich
Start-subtitle: Start - Ãœber mich
copyright-text: '&copy; 2024 D. Ulbrich'

titleEN: Dennis Ulbrich | Website
Start-subtitleEN: Start - About me
